[Node]
DataDir = "/data"
NoUSB = true
HTTPHost = "0.0.0.0"
HTTPPort = 18545
HTTPVirtualHosts = ["*"]
GraphQLVirtualHosts = ["*"]
HTTPModules = ["eth", "debug", "admin", "txpool"]
IPCPath = ""

[Node.P2P]
MaxPeers = 200

[Node.HTTPTimeouts]
ReadTimeout = 120000000000
WriteTimeout = 120000000000
IdleTimeout = 120000000000
